[package]
name = "stunning-octo-adventure"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.30.0"
reqwest = { version = "0.12", features = ["blocking"] }
dom_query = "0.2" 
